[package]
name = "e2e"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[[test]]
name = "batman_number"
path = "tests/batman_number.rs"
harness = false

[dependencies]
domain = { path = "../domain" }
api = { path = "../api" }
ingest = { path = "../ingest" }
cucumber = "0.23"
tokio = { version = "1", features = ["full"] }
neo4rs = "0.8"
testcontainers-modules = { version = "0.15", features = ["neo4j"] }
reqwest = { version = "0.12", features = ["json"] }
